# Generated by Django 2.0.5 on 2018-05-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
