# Generated by Django 2.1.7 on 2019-02-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='value',
            field=models.CharField(max_length=2000),
        ),
    ]
