# Generated by Django 2.0.5 on 2018-05-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20180522_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='key',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='value',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
