# Generated by Django 2.0.5 on 2018-05-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_remove_exercise_uuid'),
        ('participant', '0003_auto_20180522_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'started'), (1, 'completed'), (2, 'opened')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise')),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='experiment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='participantaction',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.Participant'),
        ),
    ]
