# Generated by Django 2.2.5 on 2019-09-27 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0008_auto_20190927_1338"),
        ("participant", "0003_auto_20190920_1504"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="trial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="exercise.Trial",
            ),
        )
    ]
