# Generated by Django 2.0.5 on 2018-05-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_auto_20180522_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseKey'),
        ),
    ]
