# Generated by Django 2.2.6 on 2019-11-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_auto_20191115_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='participantaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='participantprofileentry',
            name='deleted_at',
        ),
    ]
