# Generated by Django 2.0.5 on 2018-05-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_auto_20180523_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='experiment',
            new_name='exercise',
        ),
    ]
