# Generated by Django 2.0.5 on 2018-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20180523_1338'),
        ('participant', '0006_auto_20180523_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='key',
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='key',
            field=models.ManyToManyField(to='exercise.ExerciseKey'),
        ),
    ]
