# Generated by Django 2.0.5 on 2018-09-10 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0017_auto_20180910_2012'),
        ('participant', '0009_auto_20180523_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantaction',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='participantaction',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmail'),
        ),
        migrations.AlterField(
            model_name='participantaction',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AlterField(
            model_name='participantaction',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participant.Participant'),
        ),
        migrations.AlterField(
            model_name='participantaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'started'), (1, 'completed'), (2, 'opened'), (3, 'unsafe_link'), (4, 'unsafe_attachment')]),
        ),
    ]
