# Generated by Django 2.0.5 on 2018-09-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0017_auto_20180910_2012'),
        ('participant', '0010_auto_20180910_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantaction',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise.ExerciseAttachment'),
        ),
    ]
