# Generated by Django 2.0.5 on 2018-09-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0011_participantaction_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='participantaction',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='participantaction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participantaction',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='participantaction',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participantaction',
            name='type',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='action_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.ParticipantAction'),
        ),
    ]
