# Generated by Django 2.2.5 on 2019-10-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_auto_20190920_1504'),
        ('users', '0002_auto_20190930_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participant.Organization'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
