# Generated by Django 2.2.5 on 2019-09-27 13:38

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_organization'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.PhishtrayUserManager()),
            ],
        ),
    ]
