language: python
python:
  - "3.6"
services:
  - mysql
env:
  -DJANGO=2.0.5 DB=mysql SECRET_KEY=supersecretkey
install:
  - pip install -r requirements.txt
script:
  - coverage run --source='.' manage.py test
  - coverage report
after_success:
  - coveralls
