version: '2'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8001
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    networks:
      - webnet
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=phishtray
    networks:
      - webnet
networks:
  webnet:
