version: '3'

services:

  db:
    image: mysql:5.7
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - "9306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=phishtray
    networks:
    - webnet

  django:
    build:
      context: ../..
      dockerfile: local.Dockerfile
    command: dockerize -wait tcp://db:3306 -timeout 60s bash -c "python3.6 manage.py makemigrations; python3.6 manage.py migrate; tail -f /dev/null"
    ports:
    - "9000:9000"
    - "9022:22"
    environment:
    - ALLOWED_HOSTS=*
    - DB_URL=mysql://root:admin@db:3306/phishtray
    - REACT_APP_HOST_BACKEND=http://cybsafe.local:9000
    - REACT_APP_HOST_FRONTEND=http://cybsafe.local:3000
    volumes:
    - ../../.:/usr/src/app
    networks:
    - webnet
    depends_on:
    - db

networks:
  webnet:
