export default {
  experimentEndManual: 'experiment_ended_manually',
  experimentEndTimeout: 'experiment_ended_timeout',
  experimentStarted: 'experiment_started',
  fileDelete: 'file_deleted',
  fileOpen: 'file_opened',
  emailOpen: 'email_opened',
  emailReply: 'email_replied',
  emailForward: 'email_forwarded',
  emailDelete: 'email_deleted',
  emailReport: 'email_reported',
  emailQuickReply: 'email_quick_reply',
  emailAttachmentDownload: 'email_attachment_download',
  emailLinkOpen: 'email_link_clicked',
  accountOpen: 'account_open',
  contactOpen: 'contact_open',
  browserClose: 'browser_closed',
  browserClick: 'webpage_click',
  browserInputChange: 'webpage_entry',
  browserInputLoginCrendentials: 'webpage_login_credentials_entered',
  browserForgottenPassword: 'webpage_forgotten_password',
  browserSubmittedDetails: 'webpage_login_credentials_submitted',
  browserUserSignUp: 'webpage_user_signup',
  trainingLinkClick: 'training_link_clicked',
  trainingReleaseCodeConfirm: 'training_release_code_confirm',
};
