export default {
  experimentEndManual: 'experiment_ended_manually',
  experimentEndTimeout: 'experiment_ended_timeout',
  experimentStarted: 'experiment_started',
  fileDelete: 'file_delete',
  fileOpen: 'file_open',
  emailOpen: 'email_open',
  emailReply: 'email_reply',
  emailForward: 'email_forward',
  emailDelete: 'email_delete',
  emailReport: 'email_report',
  emailQuickReply: 'email_quick_reply',
  emailAttachmentDownload: 'email_attachment_download',
  emailLinkOpen: 'email_link_open',
  accountOpen: 'account_open',
  contactOpen: 'contact_open',
  browserClose: 'close_browser',
  browserClick: 'webpage_click',
  browserInputChange: 'webpage_entry',
  browserSubmittedDetails: 'webpage_login_credentials_submitted',
};
