# Generated by Django 2.1.2 on 2018-10-12 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicsInfo',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('question_type', models.IntegerField(choices=[(0, 'number'), (1, 'string')])),
                ('question', models.CharField(blank=True, max_length=180, null=True)),
                ('required', models.BooleanField(default=False, help_text='Mark question mandatory on the participant form.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('afterword', models.TextField(blank=True, null=True)),
                ('length_minutes', models.IntegerField()),
                ('demographics', models.ManyToManyField(blank=True, to='exercise.DemographicsInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseEmail',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('from_address', models.CharField(blank=True, max_length=250, null=True)),
                ('from_name', models.CharField(blank=True, max_length=250, null=True)),
                ('from_profile_img_url', models.CharField(blank=True, max_length=150, null=True)),
                ('from_role', models.CharField(blank=True, max_length=50, null=True)),
                ('to_address', models.CharField(blank=True, max_length=250, null=True)),
                ('to_name', models.CharField(blank=True, max_length=250, null=True)),
                ('to_profile_img_url', models.CharField(blank=True, max_length=150, null=True)),
                ('to_role', models.CharField(blank=True, max_length=50, null=True)),
                ('phish_type', models.IntegerField(choices=[(0, 'phishing'), (1, 'regular'), (2, 'etray')])),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseEmailProperties',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reveal_time', models.PositiveIntegerField(blank=True, help_text='Time in seconds.', null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmail')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseEmailReply',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reply_type', models.IntegerField(choices=[(0, 'reply'), (1, 'forward')], null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseFile',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('img_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseURL',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('actual_url', models.CharField(blank=True, max_length=250, null=True)),
                ('real_url', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.IntegerField(choices=[(0, 'phishing'), (1, 'regular'), (2, 'etray')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseWebPages',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.IntegerField(choices=[(0, 'phishing'), (1, 'regular'), (2, 'etray')])),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exerciseurl',
            name='web_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseWebPages'),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='exercise.ExerciseFile'),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmail'),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='replies',
            field=models.ManyToManyField(blank=True, to='exercise.ExerciseEmailReply'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='emails',
            field=models.ManyToManyField(blank=True, to='exercise.ExerciseEmail'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='files',
            field=models.ManyToManyField(blank=True, to='exercise.ExerciseFile'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseemailproperties',
            unique_together={('exercise', 'email')},
        ),
    ]
