# Generated by Django 2.0.5 on 2018-09-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicsinfo',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'number'), (1, 'string')]),
        ),
    ]
