# Generated by Django 2.0.5 on 2018-05-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='uuid',
        ),
    ]
