# Generated by Django 2.0.5 on 2018-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseemail',
            name='from_profile_img_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='from_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='to_profile_img_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='to_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
