# Generated by Django 2.0.5 on 2018-10-11 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20180920_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseEmailProperties',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reveal_time', models.PositiveIntegerField(blank=True, help_text='Time in seconds.', null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmail')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='email_reveal_times',
        ),
        migrations.AddField(
            model_name='exerciseemailproperties',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseemailproperties',
            unique_together={('exercise', 'email')},
        ),
    ]
