# Generated by Django 2.1.2 on 2018-10-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20181016_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseemail',
            options={'ordering': ['sort_order']},
        ),
    ]
