# Generated by Django 2.0.5 on 2018-09-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20180927_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseemailrevealtime',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmail'),
        ),
    ]
