# Generated by Django 2.2.5 on 2019-09-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20181017_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographicsinfo',
            options={'verbose_name_plural': 'Demographic Info'},
        ),
        migrations.AlterModelOptions(
            name='exerciseemailproperties',
            options={'verbose_name_plural': 'Exercise email properties'},
        ),
        migrations.AlterModelOptions(
            name='exercisewebpages',
            options={'verbose_name_plural': 'Exercise web pages'},
        ),
    ]
