# Generated by Django 2.0.5 on 2018-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercisekey_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisekey',
            name='type',
            field=models.IntegerField(choices=[(0, 'number'), (1, 'text')]),
        ),
    ]
