# Generated by Django 2.2.5 on 2019-09-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20190924_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='training_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
