# Generated by Django 2.2.5 on 2019-09-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20190924_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseemail',
            name='phish_type',
            field=models.IntegerField(choices=[(0, 'phishing'), (1, 'regular')]),
        ),
        migrations.AlterField(
            model_name='exerciseurl',
            name='type',
            field=models.IntegerField(choices=[(0, 'phishing'), (1, 'regular')]),
        ),
        migrations.AlterField(
            model_name='exercisewebpages',
            name='type',
            field=models.IntegerField(choices=[(0, 'phishing'), (1, 'regular')]),
        ),
    ]
