# Generated by Django 2.2.5 on 2019-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20190924_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='debrief',
            field=models.BooleanField(default=False, help_text='Should user receive a phishing debrief at the end of the exercise?'),
        ),
    ]
