# Generated by Django 2.2.5 on 2019-09-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20190925_1407'),
        ('exercise', '0006_exercise_debrief'),
        ('exercise', '0006_exercise_training_link'),
    ]

    operations = [
    ]
