# Generated by Django 2.2.5 on 2019-10-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20190930_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='debrief',
            field=models.BooleanField(default=False, help_text='Should participants receive a phishing debrief at the end of the exercise?'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='training_link',
            field=models.CharField(blank=True, help_text='Defaults to a training URI provided by Cybsafe.', max_length=200),
        ),
    ]
