# Generated by Django 2.0.5 on 2018-05-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20180524_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseEmailReplies',
            new_name='ExerciseEmailReply',
        ),
    ]
