# Generated by Django 2.2.5 on 2019-10-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20191003_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseURL',
        ),
    ]
