# Generated by Django 2.2.5 on 2019-09-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20190927_1338'),
        ('exercise', '0006_auto_20190930_1018'),
    ]

    operations = [
    ]
