# Generated by Django 2.2.5 on 2019-10-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0008_delete_exerciseurl"),
        ("exercise", "0008_auto_20191010_1359"),
    ]

    operations = []
