# Generated by Django 2.2.6 on 2019-10-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20191010_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseURL',
        ),
    ]
