# Generated by Django 2.0.5 on 2018-06-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_auto_20180524_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseemail',
            old_name='email_from_email',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='exerciseemail',
            old_name='email_from_name',
            new_name='from_name',
        ),
    ]
