# Generated by Django 2.2.5 on 2019-10-11 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_delete_exerciseurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseWebPageReleaseCode',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('release_code', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exerciseemailproperties',
            name='intercept_exercise',
            field=models.BooleanField(default=False, help_text='If selected, participants will be prevented to proceed with the exercise         until they enter the correct release code.'),
        ),
        migrations.AddField(
            model_name='exerciseemailproperties',
            name='web_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseWebPage'),
        ),
        migrations.AddField(
            model_name='exerciseemailproperties',
            name='release_codes',
            field=models.ManyToManyField(help_text='Accepted codes.      Participants, who have been intercepted, will need to provide one of the selected codes      to proceed with the exercise.', to='exercise.ExerciseWebPageReleaseCode'),
        ),
    ]
