# Generated by Django 2.2.6 on 2019-10-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_auto_20191011_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exercise.Exercise'),
        ),
    ]
