# Generated by Django 2.0.5 on 2018-06-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_auto_20180626_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseemail',
            old_name='type',
            new_name='phish_type',
        ),
    ]
