# Generated by Django 2.0.5 on 2018-06-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_auto_20180626_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseemailreply',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='exerciseemailreply',
            name='reply_type',
            field=models.IntegerField(choices=[(0, 'reply'), (1, 'forward')], null=True),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='to_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='to_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
