# Generated by Django 2.0.5 on 2018-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_auto_20180627_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='emails',
            field=models.ManyToManyField(to='exercise.ExerciseEmail'),
        ),
    ]
