# Generated by Django 2.2.5 on 2019-10-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_auto_20191018_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseemailproperties',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
