# Generated by Django 2.2.6 on 2019-10-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("exercise", "0013_auto_20191018_1513")]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="trial_version",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("trial_version", "copied_from"), name="exercise_trial"
            ),
        ),
    ]
