# Generated by Django 2.0.5 on 2018-06-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_exercise_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseemail',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='exercise.ExerciseAttachment'),
        ),
        migrations.AlterField(
            model_name='exerciseemail',
            name='replies',
            field=models.ManyToManyField(blank=True, to='exercise.ExerciseEmailReply'),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='belongs_to',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmail'),
        ),
    ]
