# Generated by Django 2.2.5 on 2019-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_auto_20191018_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseemailproperties',
            name='date_received',
            field=models.DateTimeField(blank=True, help_text='If date is provided reveal time will be automatically set to 0.', null=True),
        ),
    ]
