# Generated by Django 2.2.6 on 2019-10-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_auto_20191018_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='initial_trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exercise_initial_trial', to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='trial_version',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('initial_trial', 'trial_version'), name='exercise_trial'),
        ),
    ]
