# Generated by Django 2.0.5 on 2018-06-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_exercise_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseemail',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmail'),
        ),
    ]
