# Generated by Django 2.0.5 on 2018-06-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0014_auto_20180628_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='emails',
            field=models.ManyToManyField(blank=True, to='exercise.ExerciseEmail'),
        ),
    ]
