# Generated by Django 2.2.6 on 2019-10-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0015_exerciseemailproperties_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.Exercise'),
        ),
    ]
