# Generated by Django 2.0.5 on 2018-08-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0015_auto_20180628_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.IntegerField(choices=[(0, 'email_reply'), (1, 'email_attachment_open')])),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseAttachment')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmail')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmailReply')),
            ],
        ),
    ]
