# Generated by Django 2.0.5 on 2018-08-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0015_auto_20180628_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseEmailsThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveal_time', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='temporary_name', to='exercise.ExerciseEmail'),
        ),
        migrations.AddField(
            model_name='exerciseemailsthrough',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='exerciseemailsthrough',
            name='exerciseemail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseEmail'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='emails2',
            field=models.ManyToManyField(blank=True, through='exercise.ExerciseEmailsThrough', to='exercise.ExerciseEmail'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseemailsthrough',
            unique_together={('exercise', 'exerciseemail')},
        ),
    ]
