# Generated by Django 2.0.5 on 2018-08-22 23:25

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0015_auto_20180628_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='email_reveal_times',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
