# Generated by Django 2.0.5 on 2018-08-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_exerciseaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseemailreply',
            options={'verbose_name_plural': 'Exercise email replies'},
        ),
        migrations.AlterModelOptions(
            name='exercisewebpages',
            options={'verbose_name_plural': 'Exercise web pages'},
        ),
        migrations.AddField(
            model_name='exerciseaction',
            name='milliseconds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
