# Generated by Django 2.0.5 on 2018-09-10 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_exercise_email_reveal_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='exercise',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciseemail',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exerciseemail',
            name='phish_type',
            field=models.IntegerField(choices=[(0, 'phishing'), (1, 'regular'), (2, 'etray')]),
        ),
        migrations.AlterField(
            model_name='exerciseurl',
            name='type',
            field=models.IntegerField(choices=[(0, 'phishing'), (1, 'regular'), (2, 'etray')]),
        ),
        migrations.AlterField(
            model_name='exercisewebpages',
            name='type',
            field=models.IntegerField(choices=[(0, 'phishing'), (1, 'regular'), (2, 'etray')]),
        ),
    ]
