# Generated by Django 2.2.6 on 2019-10-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_auto_20191025_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='copied_from',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='initial_trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_initial_trial', to='exercise.Exercise'),
        ),
    ]
