# Generated by Django 2.0.5 on 2018-08-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_new_intermediary_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='emails',
        ),
    ]
