# Generated by Django 2.0.5 on 2018-08-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0017_remove_attr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='emails2',
            new_name='emails',
        ),
    ]
