# Generated by Django 2.2.5 on 2019-11-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_auto_20190920_1504'),
        ('exercise', '0017_auto_20191028_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisewebpage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participant.Organization'),
        ),
        migrations.AddField(
            model_name='exercisewebpagereleasecode',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participant.Organization'),
        ),
    ]
