# Generated by Django 2.2.5 on 2019-11-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0018_auto_20191104_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseemail',
            name='from_profile_img_url',
        ),
        migrations.RemoveField(
            model_name='exerciseemail',
            name='to_profile_img_url',
        ),
    ]
