# Generated by Django 2.2.5 on 2019-11-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_auto_20190920_1504'),
        ('exercise', '0019_auto_20191107_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseemail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participant.Organization'),
        ),
        migrations.AddField(
            model_name='exerciseemailreply',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participant.Organization'),
        ),
        migrations.AddField(
            model_name='exercisefile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participant.Organization'),
        ),
    ]
