# Generated by Django 2.2.6 on 2019-11-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0020_auto_20191108_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='demographicsinfo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='emailreplytaskscore',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exerciseemail',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exerciseemailproperties',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exerciseemailreply',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exercisefile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exercisetask',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exercisewebpage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='exercisewebpagereleasecode',
            name='deleted_at',
        ),
    ]
