# Generated by Django 2.2.5 on 2019-11-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0021_demographicsinfo_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='organisation',
            new_name='organization',
        ),
    ]
