# Generated by Django 2.2.5 on 2019-11-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_auto_20191115_1728'),
        ('exercise', '0022_demographicsinfo_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreplytaskscore',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participant.Organization'),
        ),
        migrations.AddField(
            model_name='exercisetask',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participant.Organization'),
        ),
    ]
