# Generated by Django 2.2.6 on 2019-12-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0005_auto_20191115_1728"),
        ("exercise", "0023_auto_20191119_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisewebpage",
            name="url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="exercisewebpagereleasecode",
            name="release_code",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name="exercisewebpage", unique_together={("url", "organization")},
        ),
        migrations.AlterUniqueTogether(
            name="exercisewebpagereleasecode",
            unique_together={("release_code", "organization")},
        ),
    ]
